server:
  port: 8080

spring:
  datasource:
    name: kpl
    url: jdbc:mysql://127.0.0.1:3306/kpl?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: kpl
    password: kpl
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.kpl.model  # 注意：对应实体类的路径

