spring:




  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kpl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: kpl
    password: kpl
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    smaxActive: 20
    maxWait: 60000

  mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
    type-aliases-package: com.cwh.springbootMybatis.entity
